// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:3000' | (string & {});
};

/**
 * Body_login_access_token_api_v1_login_access_token_post
 */
export type BodyLoginAccessTokenApiV1LoginAccessTokenPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ChargeLogRead
 */
export type ChargeLogRead = {
    status: ChargeStatus;
    /**
     * Energy Wh
     *
     * Dodaná energie ve Wh
     */
    energy_wh?: number | null;
    /**
     * Price
     */
    price?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * User Id
     */
    user_id: number | null;
    /**
     * Charger Id
     */
    charger_id: number | null;
    /**
     * Connector Id
     */
    connector_id: number | null;
    /**
     * Rfid Card Id
     */
    rfid_card_id: number | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string | null;
};

/**
 * ChargeStatus
 */
export type ChargeStatus = 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * ChargerCreate
 *
 * Model pro vytváření nabíječky uživatelem.
 */
export type ChargerCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    /**
     * Street
     */
    street?: string | null;
    /**
     * House Number
     */
    house_number?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
    /**
     * Owner Id
     */
    owner_id?: number | null;
};

/**
 * ChargerRead
 *
 * Model pro čtení (odpověď API).
 * Zde vracíme i technická data, aby je uživatel viděl,
 * i když je nemůže editovat.
 */
export type ChargerRead = {
    /**
     * Name
     */
    name: string;
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    /**
     * Street
     */
    street?: string | null;
    /**
     * House Number
     */
    house_number?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Enabled
     */
    is_enabled: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Ocpp Id
     */
    ocpp_id: string;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Vendor
     */
    vendor?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Serial Number
     */
    serial_number?: string | null;
    /**
     * Firmware Version
     */
    firmware_version?: string | null;
    /**
     * Connectors
     */
    connectors?: Array<ConnectorRead>;
};

/**
 * ChargerUpdate
 *
 * Model pro editaci uživatelem.
 * Obsahuje jen to, co smí uživatel změnit (název, adresa, poloha).
 */
export type ChargerUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Street
     */
    street?: string | null;
    /**
     * House Number
     */
    house_number?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Postal Code
     */
    postal_code?: string | null;
    /**
     * Region
     */
    region?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean | null;
};

/**
 * ConnectorRead
 */
export type ConnectorRead = {
    /**
     * Ocpp Number
     */
    ocpp_number: number;
    type?: ConnectorType | null;
    current_type?: CurrentType | null;
    /**
     * Max Power W
     */
    max_power_w?: number | null;
    /**
     * Price Per Kwh
     */
    price_per_kwh?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Charger Id
     */
    charger_id: number;
    /**
     * Status
     */
    status?: string | null;
};

/**
 * ConnectorType
 */
export type ConnectorType = 'Type1' | 'Type2' | 'CCS' | 'CHAdeMO' | 'Tesla';

/**
 * ConnectorUpdate
 */
export type ConnectorUpdate = {
    type?: ConnectorType | null;
    current_type?: CurrentType | null;
    /**
     * Max Power W
     */
    max_power_w?: number | null;
    /**
     * Price Per Kwh
     */
    price_per_kwh?: number | string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * CurrentType
 */
export type CurrentType = 'AC' | 'DC';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RFIDCardCreate
 */
export type RfidCardCreate = {
    /**
     * Card Uid
     */
    card_uid: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Enabled
     */
    is_enabled?: boolean;
    /**
     * Owner Id
     */
    owner_id?: number | null;
};

/**
 * RFIDCardRead
 */
export type RfidCardRead = {
    /**
     * Card Uid
     */
    card_uid: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Enabled
     */
    is_enabled: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RFIDCardUpdate
 */
export type RfidCardUpdate = {
    /**
     * Card Uid
     */
    card_uid?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Enabled
     */
    is_enabled?: boolean | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    role?: UserRole | null;
    /**
     * Balance
     */
    balance?: number | string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string;
    role: UserRole;
    /**
     * Balance
     */
    balance: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserRole
 */
export type UserRole = 'user' | 'owner' | 'admin';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    role?: UserRole | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Old Password
     */
    old_password?: string | null;
    /**
     * Balance
     */
    balance?: number | string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostData = {
    body: BodyLoginAccessTokenApiV1LoginAccessTokenPost;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginAccessTokenApiV1LoginAccessTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostError = LoginAccessTokenApiV1LoginAccessTokenPostErrors[keyof LoginAccessTokenApiV1LoginAccessTokenPostErrors];

export type LoginAccessTokenApiV1LoginAccessTokenPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAccessTokenApiV1LoginAccessTokenPostResponse = LoginAccessTokenApiV1LoginAccessTokenPostResponses[keyof LoginAccessTokenApiV1LoginAccessTokenPostResponses];

export type GetUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Show All
         */
        show_all?: boolean;
    };
    url: '/api/v1/users/';
};

export type GetUsersApiV1UsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersApiV1UsersGetError = GetUsersApiV1UsersGetErrors[keyof GetUsersApiV1UsersGetErrors];

export type GetUsersApiV1UsersGetResponses = {
    /**
     * Response Get Users Api V1 Users  Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type GetUsersApiV1UsersGetResponse = GetUsersApiV1UsersGetResponses[keyof GetUsersApiV1UsersGetResponses];

export type CreateUserApiV1UsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserApiV1UsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1UsersPostError = CreateUserApiV1UsersPostErrors[keyof CreateUserApiV1UsersPostErrors];

export type CreateUserApiV1UsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type CreateUserApiV1UsersPostResponse = CreateUserApiV1UsersPostResponses[keyof CreateUserApiV1UsersPostResponses];

export type ReadUserMeApiV1UsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type ReadUserMeApiV1UsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type ReadUserMeApiV1UsersMeGetResponse = ReadUserMeApiV1UsersMeGetResponses[keyof ReadUserMeApiV1UsersMeGetResponses];

export type DeleteUserApiV1UsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserApiV1UsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiV1UsersUserIdDeleteError = DeleteUserApiV1UsersUserIdDeleteErrors[keyof DeleteUserApiV1UsersUserIdDeleteErrors];

export type DeleteUserApiV1UsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserApiV1UsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetUserApiV1UsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiV1UsersUserIdGetError = GetUserApiV1UsersUserIdGetErrors[keyof GetUserApiV1UsersUserIdGetErrors];

export type GetUserApiV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserApiV1UsersUserIdGetResponse = GetUserApiV1UsersUserIdGetResponses[keyof GetUserApiV1UsersUserIdGetResponses];

export type UpdateUserApiV1UsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserApiV1UsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiV1UsersUserIdPatchError = UpdateUserApiV1UsersUserIdPatchErrors[keyof UpdateUserApiV1UsersUserIdPatchErrors];

export type UpdateUserApiV1UsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserApiV1UsersUserIdPatchResponse = UpdateUserApiV1UsersUserIdPatchResponses[keyof UpdateUserApiV1UsersUserIdPatchResponses];

export type GetChargersApiV1ChargersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Mine
         */
        mine?: boolean;
    };
    url: '/api/v1/chargers';
};

export type GetChargersApiV1ChargersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChargersApiV1ChargersGetError = GetChargersApiV1ChargersGetErrors[keyof GetChargersApiV1ChargersGetErrors];

export type GetChargersApiV1ChargersGetResponses = {
    /**
     * Response Get Chargers Api V1 Chargers Get
     *
     * Successful Response
     */
    200: Array<ChargerRead>;
};

export type GetChargersApiV1ChargersGetResponse = GetChargersApiV1ChargersGetResponses[keyof GetChargersApiV1ChargersGetResponses];

export type CreateChargerApiV1ChargersPostData = {
    body: ChargerCreate;
    path?: never;
    query?: never;
    url: '/api/v1/chargers';
};

export type CreateChargerApiV1ChargersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChargerApiV1ChargersPostError = CreateChargerApiV1ChargersPostErrors[keyof CreateChargerApiV1ChargersPostErrors];

export type CreateChargerApiV1ChargersPostResponses = {
    /**
     * Successful Response
     */
    201: ChargerRead;
};

export type CreateChargerApiV1ChargersPostResponse = CreateChargerApiV1ChargersPostResponses[keyof CreateChargerApiV1ChargersPostResponses];

export type DeleteChargerApiV1ChargersChargerIdDeleteData = {
    body?: never;
    path: {
        /**
         * Charger Id
         */
        charger_id: number;
    };
    query?: never;
    url: '/api/v1/chargers/{charger_id}';
};

export type DeleteChargerApiV1ChargersChargerIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteChargerApiV1ChargersChargerIdDeleteError = DeleteChargerApiV1ChargersChargerIdDeleteErrors[keyof DeleteChargerApiV1ChargersChargerIdDeleteErrors];

export type DeleteChargerApiV1ChargersChargerIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteChargerApiV1ChargersChargerIdDeleteResponse = DeleteChargerApiV1ChargersChargerIdDeleteResponses[keyof DeleteChargerApiV1ChargersChargerIdDeleteResponses];

export type GetChargerApiV1ChargersChargerIdGetData = {
    body?: never;
    path: {
        /**
         * Charger Id
         */
        charger_id: number;
    };
    query?: never;
    url: '/api/v1/chargers/{charger_id}';
};

export type GetChargerApiV1ChargersChargerIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChargerApiV1ChargersChargerIdGetError = GetChargerApiV1ChargersChargerIdGetErrors[keyof GetChargerApiV1ChargersChargerIdGetErrors];

export type GetChargerApiV1ChargersChargerIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChargerRead;
};

export type GetChargerApiV1ChargersChargerIdGetResponse = GetChargerApiV1ChargersChargerIdGetResponses[keyof GetChargerApiV1ChargersChargerIdGetResponses];

export type UpdateChargerApiV1ChargersChargerIdPatchData = {
    body: ChargerUpdate;
    path: {
        /**
         * Charger Id
         */
        charger_id: number;
    };
    query?: never;
    url: '/api/v1/chargers/{charger_id}';
};

export type UpdateChargerApiV1ChargersChargerIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateChargerApiV1ChargersChargerIdPatchError = UpdateChargerApiV1ChargersChargerIdPatchErrors[keyof UpdateChargerApiV1ChargersChargerIdPatchErrors];

export type UpdateChargerApiV1ChargersChargerIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ChargerRead;
};

export type UpdateChargerApiV1ChargersChargerIdPatchResponse = UpdateChargerApiV1ChargersChargerIdPatchResponses[keyof UpdateChargerApiV1ChargersChargerIdPatchResponses];

export type GetConnectorApiV1ConnectorsConnectorIdGetData = {
    body?: never;
    path: {
        /**
         * Connector Id
         */
        connector_id: number;
    };
    query?: never;
    url: '/api/v1/connectors/{connector_id}';
};

export type GetConnectorApiV1ConnectorsConnectorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectorApiV1ConnectorsConnectorIdGetError = GetConnectorApiV1ConnectorsConnectorIdGetErrors[keyof GetConnectorApiV1ConnectorsConnectorIdGetErrors];

export type GetConnectorApiV1ConnectorsConnectorIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConnectorRead;
};

export type GetConnectorApiV1ConnectorsConnectorIdGetResponse = GetConnectorApiV1ConnectorsConnectorIdGetResponses[keyof GetConnectorApiV1ConnectorsConnectorIdGetResponses];

export type UpdateConnectorApiV1ConnectorsConnectorIdPatchData = {
    body: ConnectorUpdate;
    path: {
        /**
         * Connector Id
         */
        connector_id: number;
    };
    query?: never;
    url: '/api/v1/connectors/{connector_id}';
};

export type UpdateConnectorApiV1ConnectorsConnectorIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConnectorApiV1ConnectorsConnectorIdPatchError = UpdateConnectorApiV1ConnectorsConnectorIdPatchErrors[keyof UpdateConnectorApiV1ConnectorsConnectorIdPatchErrors];

export type UpdateConnectorApiV1ConnectorsConnectorIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ConnectorRead;
};

export type UpdateConnectorApiV1ConnectorsConnectorIdPatchResponse = UpdateConnectorApiV1ConnectorsConnectorIdPatchResponses[keyof UpdateConnectorApiV1ConnectorsConnectorIdPatchResponses];

export type GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetData = {
    body?: never;
    path: {
        /**
         * Identity
         */
        identity: string;
        /**
         * Ocpp Connector Id
         */
        ocpp_connector_id: number;
    };
    query?: never;
    url: '/api/v1/connectors/ocpp/{identity}/{ocpp_connector_id}';
};

export type GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetError = GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetErrors[keyof GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetErrors];

export type GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConnectorRead;
};

export type GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetResponse = GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetResponses[keyof GetConnectorByOcppDataApiV1ConnectorsOcppIdentityOcppConnectorIdGetResponses];

export type GetCardsApiV1RfidCardsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Show All
         */
        show_all?: boolean;
    };
    url: '/api/v1/rfid-cards/';
};

export type GetCardsApiV1RfidCardsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCardsApiV1RfidCardsGetError = GetCardsApiV1RfidCardsGetErrors[keyof GetCardsApiV1RfidCardsGetErrors];

export type GetCardsApiV1RfidCardsGetResponses = {
    /**
     * Response Get Cards Api V1 Rfid Cards  Get
     *
     * Successful Response
     */
    200: Array<RfidCardRead>;
};

export type GetCardsApiV1RfidCardsGetResponse = GetCardsApiV1RfidCardsGetResponses[keyof GetCardsApiV1RfidCardsGetResponses];

export type CreateCardApiV1RfidCardsPostData = {
    body: RfidCardCreate;
    path?: never;
    query?: never;
    url: '/api/v1/rfid-cards/';
};

export type CreateCardApiV1RfidCardsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCardApiV1RfidCardsPostError = CreateCardApiV1RfidCardsPostErrors[keyof CreateCardApiV1RfidCardsPostErrors];

export type CreateCardApiV1RfidCardsPostResponses = {
    /**
     * Successful Response
     */
    201: RfidCardRead;
};

export type CreateCardApiV1RfidCardsPostResponse = CreateCardApiV1RfidCardsPostResponses[keyof CreateCardApiV1RfidCardsPostResponses];

export type DeleteCardApiV1RfidCardsCardIdDeleteData = {
    body?: never;
    path: {
        /**
         * Card Id
         */
        card_id: number;
    };
    query?: never;
    url: '/api/v1/rfid-cards/{card_id}';
};

export type DeleteCardApiV1RfidCardsCardIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCardApiV1RfidCardsCardIdDeleteError = DeleteCardApiV1RfidCardsCardIdDeleteErrors[keyof DeleteCardApiV1RfidCardsCardIdDeleteErrors];

export type DeleteCardApiV1RfidCardsCardIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCardApiV1RfidCardsCardIdDeleteResponse = DeleteCardApiV1RfidCardsCardIdDeleteResponses[keyof DeleteCardApiV1RfidCardsCardIdDeleteResponses];

export type GetCardApiV1RfidCardsCardIdGetData = {
    body?: never;
    path: {
        /**
         * Card Id
         */
        card_id: number;
    };
    query?: never;
    url: '/api/v1/rfid-cards/{card_id}';
};

export type GetCardApiV1RfidCardsCardIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCardApiV1RfidCardsCardIdGetError = GetCardApiV1RfidCardsCardIdGetErrors[keyof GetCardApiV1RfidCardsCardIdGetErrors];

export type GetCardApiV1RfidCardsCardIdGetResponses = {
    /**
     * Successful Response
     */
    200: RfidCardRead;
};

export type GetCardApiV1RfidCardsCardIdGetResponse = GetCardApiV1RfidCardsCardIdGetResponses[keyof GetCardApiV1RfidCardsCardIdGetResponses];

export type UpdateCardApiV1RfidCardsCardIdPatchData = {
    body: RfidCardUpdate;
    path: {
        /**
         * Card Id
         */
        card_id: number;
    };
    query?: never;
    url: '/api/v1/rfid-cards/{card_id}';
};

export type UpdateCardApiV1RfidCardsCardIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCardApiV1RfidCardsCardIdPatchError = UpdateCardApiV1RfidCardsCardIdPatchErrors[keyof UpdateCardApiV1RfidCardsCardIdPatchErrors];

export type UpdateCardApiV1RfidCardsCardIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RfidCardRead;
};

export type UpdateCardApiV1RfidCardsCardIdPatchResponse = UpdateCardApiV1RfidCardsCardIdPatchResponses[keyof UpdateCardApiV1RfidCardsCardIdPatchResponses];

export type GetCardByUidApiV1RfidCardsLookupUidGetData = {
    body?: never;
    path: {
        /**
         * Uid
         */
        uid: string;
    };
    query?: never;
    url: '/api/v1/rfid-cards/lookup/{uid}';
};

export type GetCardByUidApiV1RfidCardsLookupUidGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCardByUidApiV1RfidCardsLookupUidGetError = GetCardByUidApiV1RfidCardsLookupUidGetErrors[keyof GetCardByUidApiV1RfidCardsLookupUidGetErrors];

export type GetCardByUidApiV1RfidCardsLookupUidGetResponses = {
    /**
     * Successful Response
     */
    200: RfidCardRead;
};

export type GetCardByUidApiV1RfidCardsLookupUidGetResponse = GetCardByUidApiV1RfidCardsLookupUidGetResponses[keyof GetCardByUidApiV1RfidCardsLookupUidGetResponses];

export type GetMyTransactionsApiV1TransactionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Charger Id
         */
        charger_id?: number | null;
        /**
         * As Owner
         */
        as_owner?: boolean;
    };
    url: '/api/v1/transactions/';
};

export type GetMyTransactionsApiV1TransactionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyTransactionsApiV1TransactionsGetError = GetMyTransactionsApiV1TransactionsGetErrors[keyof GetMyTransactionsApiV1TransactionsGetErrors];

export type GetMyTransactionsApiV1TransactionsGetResponses = {
    /**
     * Response Get My Transactions Api V1 Transactions  Get
     *
     * Successful Response
     */
    200: Array<ChargeLogRead>;
};

export type GetMyTransactionsApiV1TransactionsGetResponse = GetMyTransactionsApiV1TransactionsGetResponses[keyof GetMyTransactionsApiV1TransactionsGetResponses];

export type GetTransactionDetailApiV1TransactionsTransactionIdGetData = {
    body?: never;
    path: {
        /**
         * Transaction Id
         */
        transaction_id: number;
    };
    query?: never;
    url: '/api/v1/transactions/{transaction_id}';
};

export type GetTransactionDetailApiV1TransactionsTransactionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTransactionDetailApiV1TransactionsTransactionIdGetError = GetTransactionDetailApiV1TransactionsTransactionIdGetErrors[keyof GetTransactionDetailApiV1TransactionsTransactionIdGetErrors];

export type GetTransactionDetailApiV1TransactionsTransactionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChargeLogRead;
};

export type GetTransactionDetailApiV1TransactionsTransactionIdGetResponse = GetTransactionDetailApiV1TransactionsTransactionIdGetResponses[keyof GetTransactionDetailApiV1TransactionsTransactionIdGetResponses];
